### ISSUE TITLE
Content loading takes time

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#23]
While opening any homework or Lesson the requires content are taking lots of time to display final content. There are multiple splash screen appears after 30 seconds of blank screen. some time it takes 2-3 minute to load the final content.

**Comment by manasghosh81** [comment]
@mayank2k2 :Regarding content loading ,application just open the file.The actual file may contains a lot of files that may contains the mathml. It is also depends on the server infrastructure

**Comment by mayank2k2** [comment]
@manasghosh81 what is current configuration of mathjax server?

and how can we remove multiple screen and have single screen instead of showing 3 different screen.  
'Loading'
'Loading Fonts'
'Loading Content'

**Comment by manasghosh81** [comment]
These 3 loading files are there as per current implementation.Then we need to change the way  zippy is implemented.

**Comment by sumitmago** [comment]
Hi,
  What does it takes to load it efficiently? Since it is demo so it will be great to load fastest way possible.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
Closing this as now as this need current implementation changes the way zippy is implemented.
