### ISSUE TITLE
Re-sending welcome letter to school admin doen't include host name in prod environemnt

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#28]
while want to retrieve the password of School admin.
I found that this doesn't contain the host name.

Dear SUMIT MAGO,
Your email address has been used to register an account on Oxford Maths
You have been registered in: OUP TEST SCHOOL
Your role is: School Administrator
To start using your account, please sign in at [hostName] with your username and temporary password mentioned below. You need to change the password after signing in.
Username: school-admin
Password: OUPMath@125
If you have any questions, please email Customer Support at oxfordmathsindia@oup.com.
Best wishes,
Oxford Maths Team
Customer Support

**Comment by pankaj44** [comment]
We have investigated the issue and found that we need to replace the hostName in application code .It is small changes there is no relation between issue#24 where we have done the URL redirection for that domain (uat.oxfordmath.co.in) in pigu.html and other places. We will do the desire changes and deployed it in next build (tomorrow build).

**Comment by mayank2k2** [comment]
Manas/Pankaj,
I want to know how this has broken as this was working before.

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
Mayank,
 The school admin will receive a email after the school registration.The body of the email is based on  a standard template which contain a key called [hostname].This key has been replaced from application code by the hostname  specified in web-config file.The [hostname] has been used in template  to maintain the same template and work the code base seamlessly in different environment

There is a two cases where school admin is getting this email
Case 1:- At the time of  school registration.
Case 2:- Search the school and re-send the email.
In case 1  The C# code that sending the email where the key [hostname]  is replace by the config host name. Hence once we have changed the config entry with appropriate domain name that changes has been reflected in the email body that school admin is receiving.

But in case 2  of re- send the email for school registration does not  contain any line that basically replace the hostname .That's why this error is happening.

This problem is there from beginning.

We have fixed this issue.It will be available in UAT today and Prod tomorrow
Regards,
Pankaj Kumar.

**Comment by mayank2k2** [comment]
Pankaj,
First this is not from beginning we used to get welcome letter with proper and this has already tested in UAT.
And second why there is 2 different logic/code one for first time welcome letter and another for resend welcome letter

What do you mean ?
But in case 2 of re- send the email for school registration does not contain any line that basically replace the hostname .That's why this error is happening.

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
![image](https://cloud.githubusercontent.com/assets/16384541/15044019/8242ddfa-12ef-11e6-8098-da3797d78fbe.png)

**Comment by mayank2k2** [comment]
Pankaj,
I like the detail explanation about the issue its cause and resolution and its testing scope mention in github.
I hope to keep it for other issue as well so that we should know more about the issue.

@Manas We can discuss the format for final comment when you are marking the issue as Fixed in github.

Thanks,
Mayank Mishra

**Comment by mayank2k2** [comment]
Issues is fixed in UAT

**Comment by manasghosh81** [comment]
This changes is now available in Prod.
Root case - New change request.
Resolution - Functionality implemented
verified scenarios in UAT-
Generate welcome letter with more than 5 records

**Comment by manasghosh81** [comment]
Root case - Code issue there for a particular scenario
Resolution - Fixed the code
 verified scenarios in QC or UAT-
Resend email to school admin  after search school

**Comment by mayank2k2** [comment]
working fine in Prod
