### ISSUE TITLE
Application hang and crash on search

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfrodMaths_Prod#29]
if we search student as first name the Oxford math prod site goes hang and below message appears.

![image](https://cloud.githubusercontent.com/assets/16239450/15036790/91ddbea8-12b1-11e6-83d9-82d8a9ec2bb4.png)

**Comment by manasghosh81** [comment]
I have tried basic search with Firstname "mayank". it gives me result within 5 sec.Please see the screenshot.
![image](https://cloud.githubusercontent.com/assets/12447431/15038269/f4186a2e-12bf-11e6-911c-92f37ef9f361.png)

I have also tried with Firstname as "manas","student","teacher" etc.
All the cases it gives me result or shows be message that there "No data Found".

Is there any particular keyword that you have used.if that please let me know.

Whether you have typed the keyword of firstname before the page load .

Is it a single instance where there there may be some network issue as my network bandwidth. is 1gbps.

**Comment by mayank2k2** [comment]
@manasghosh81 we are facing the issues on using student as first name in basic search , i also cross check in sumit's laptop.

**Comment by manasghosh81** [comment]
This is happening using the "student"  as firstname  containing 10098,where as total no of user is 26073.

When try to fetch this amount of data  from db itself there is no time taken as you can view from the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/12447431/15040953/1b02a7ba-12d6-11e6-8016-0951187fdddc.png)

So there is no time is taking in fetching the data,the time is taking the binding the data to grid and binding 10000 records.

Is this a valid scenario done by OUP admin user.This should not be happened in case of school admin who is searching a firstname .If in case of this is valid scenario in future where this type school appear where a particular school has 10000 records with a singlename,then we need to change the implementation

Suggested solution is serverside paging,AWS elasctic cache,storing data in  any non SQL Database like SOLR ,MongoDB ,then search data as the you it has been done.

Please let me know your though on this.

**Comment by mayank2k2** [comment]
@manasghosh81 , @pankaj44 , This is not the way that systems can't load 10000 records and for this you need to change the implementation. 
First you send the wrong query result is application is querying for count or actual data.

If we search for first name as test then also it takes time.
Please check the code and let me issue.

**Comment by manasghosh81** [comment]
as discussed with @mayank2k2 ,TCS support team will the discuss  different option to implement the sbasic and advance search  in terms of restricts and messages and display no of records.The both OUPI and TCS will finalize a requirement after that.The actual implementation will be done after that

**Comment by manasghosh81** [comment]
@sumitmago ,@mayank2k2 
Please let us know the business requirement .TCS team suggestion as follows

For  OUP ADMIN
The basic search functionality should  be hided as there is no business value  added to functionality to OUP admin if OUP admin tries to search a user based on firstname or lastname.

If this functionality is needed in terms of business then there should be restriction  to fetch the record  200 only.If it founds  more that 200 records it should display a message "Please use the advance search  since it returns large set of records."
Advance search
The first parameter should  be schoolname(mandatory),Schoolcode-(at least 2 character)
FirstName,Username -minimum 3 character
Last name-min character needs be decided
Roll Number only be given  if user selects class and section only

For School admin

Basic search should be there but restricted to 200 users only.If it founds  more that 200 records it should display a message "Please use the advance search  since it returns large set of records."

Advance search

FirstName,Username -minimum 3 character
Last name-min character needs be decided
Roll Number only be given  if user selects class and section only

**Comment by sumitmago** [comment]
Dear Mayank,
    We discussed the design at length in our previous discussion so could you please document that and run it past me again. post that you can share it with Team TCS as a change request.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
@manasghosh81 we are working on design.

**Comment by mayank2k2** [comment]
@manasghosh81 please review the attached design and let me know if you have any question.
[Application hang and crash on search.docx](https://github.com/manasghosh81/OxfrodMaths_Prod/files/262637/Application.hang.and.crash.on.search.docx)

**Comment by pankaj44** [comment]
We are looking into it and let you know if we have any queries.

**Comment by mayank2k2** [comment]
@pankaj44 , Please update me on this
Thanks, mayank.

**Comment by pankaj44** [comment]
Hi Mayank,
I have moved this changes in UAT. Could you please check it and let me know.

**Comment by mayank2k2** [comment]
not completely fix as send mail to you.

**Comment by pankaj44** [comment]
I am working on that items.

**Comment by pankaj44** [comment]
I have done the changes and deployed in QA. Could you please check and let me know.

**Comment by mayank2k2** [comment]
Nothing is working, if i go to 2 page no data display? sort is also not working

**Comment by pankaj44** [comment]
Hi Mayank,
Could you please let me know the school name so that i can check it from from end. Also What sorting you have done like roll number,user name etc.

**Comment by mayank2k2** [comment]
Use teacher login.

Thanks,
Mayank Mishra

**Comment by pankaj44** [comment]
Hi Mayank,
Could you please check with OUPadmin login.

**Comment by mayank2k2** [comment]
Pankaj,
Have you tested properly, I have ask to test the things properly it is very embracing to get this type of feedback from team. 
1.  Why button are coming in center now?
1.  Why next button clickable and on click it hang.
2.  Why the changes are not made in utility search?
3.  Why same set of navigation button are showing?
4.  Why teachers grid is visible if I search for student ?
5.

**Comment by pankaj44** [comment]
Hi Mayank,
I have tested properly.
Could you please refresh you browser and clear the cache  and try again.
1. Why button are coming in center now?

It is implemented in that way that you are getting it in center align.Because if page size is greater than 5 than it is left align automatically.
All other defect I have checked but did not replicate in my system. Hence it would be better to join Webex and show me.

**Comment by pankaj44** [comment]
Hi Mayank,
Production deployment has been completed. 
Following entry has been done in web config file

<add key="MaxSearchResult" value="100" />
<add key="PageSize" value="10" />

![image](https://cloud.githubusercontent.com/assets/16239450/18540747/78d23114-7b3e-11e6-9296-25a46124a368.png)

**Comment by mayank2k2** [comment]
why grid is going out of screen in firefox
![image](https://cloud.githubusercontent.com/assets/16239450/18537851/ea2f87ee-7b25-11e6-8512-b733b059e087.png)

**Comment by mayank2k2** [comment]
working fine in production, so closing the issue
