### ISSUE TITLE
 Error in opening OM application

### ISSUE THREAD

**Issue by nehasehgal** [OUPMATH/OxfrodMaths_Prod#35]
![error](https://cloud.githubusercontent.com/assets/19407602/15382331/06695f70-1da7-11e6-8830-383d63cd5880.jpg)

**Comment by sumitmago** [comment]
Hi Neha,
               Why have we closed it without any revert/explanation from TCS. Let them study and write explanation at least.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by manasghosh81** [comment]
@nehasehgal :

This issue has been appeared only for a particular instance when TCS support team trying to generate the the validation and decryption key to fix some issue caused due to ssl problem.This issue will no longer appear gain as the ssl issue is fixed.

So please close this issue.If you still need further clarification please let me know.

Regards,
Manas

**Comment by nehasehgal** [comment]
This issue has been appeared only for a particular instance when TCS support team trying to generate the the validation and decryption key to fix some issue caused due to ssl problem.This issue will no longer appear gain as the ssl issue is fixed.
