### ISSUE TITLE
Validation issues #153

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfrodMaths_Prod#37]
@manasghosh81

The final XML files are kept at the following location: 
ftp://ftp.oup.co.in/OM%20files%20for%20upload_20%20May/

There are 13 files in the folder. 
[Validation_issues_16_May[1].xlsx](https://github.com/OUPMATH/OxfrodMaths_Prod/files/277310/Validation_issues_16_May.1.xlsx)

**Comment by manasghosh81** [comment]
All the 13 files has been properly placed in UAT environment.Please check those and assign back to me .We will update the same content once these 13 contents are fixed in UAT

**Comment by kirti-sharma** [comment]
Of the 13 files, three have issues:
![image](https://cloud.githubusercontent.com/assets/16831643/15499484/20928baa-21c2-11e6-8874-17c28a3a0ad5.png)

![image](https://cloud.githubusercontent.com/assets/16831643/15499473/185ea3f6-21c2-11e6-94f2-16dcb382f8d2.png)

Please resolve.

**Comment by pankaj44** [comment]
This is content issue.Could you please let us know what it is showing in offline player

**Comment by kirti-sharma** [comment]
![image](https://cloud.githubusercontent.com/assets/16831643/15502022/f7fd0c6c-21ce-11e6-8815-ccdb7adefe5a.png)

All the above files are working correct offline.

**Comment by kirti-sharma** [comment]
Please fix these three issues:
![image](https://cloud.githubusercontent.com/assets/16831643/15599471/22bd8ede-2401-11e6-9134-68a3f3f702d5.png)
![image](https://cloud.githubusercontent.com/assets/16831643/15599474/29697d88-2401-11e6-9ee0-d964a24ee996.png)

**Comment by manasghosh81** [comment]
@kirti-sharma :Please check these content in Production.These are working fine in Production which loads all the above mentioned file in less than 10 secs.

**Comment by kirti-sharma** [comment]
I am not able to regenerate the error case of the below file. I have tried it many times. 
![image](https://cloud.githubusercontent.com/assets/16831643/15648416/26337bd0-2688-11e6-97f9-b500338126e0.png)
@manasghosh81 If you could please send us the random split file with the error case (below screenshot) or otherwise send us a screenshot of the error case run on your system, we will be able to verify and close it.

![image](https://cloud.githubusercontent.com/assets/16831643/15648431/3c578aaa-2688-11e6-8b20-e27370e368ce.png)

**Comment by pankaj44** [comment]
Hi Kirti,
Could you please check it and close the issues.

**Comment by kirti-sharma** [comment]
These issues are fixed in production.
